---
# tasks file for geo_replication
# Set the georepuser variable. If not defined default to root
- name: Set Geo-replication user
  set_fact:
     georepuser: "{{ georepuser | default('root') }}"

# Run only on masternode
- name: Setup shared storage and generate keys
  import_tasks: georep_session_create.yml
  when: >
    gluster_features_georep_mastervol is defined and
    gluster_features_georep_slavevol is defined
  tags:
    - georep_session_create
