---
# Create volumes for gluster_hci
- name: Create the GlusterFS volumes
  gluster_volume:
     state: present
     name: "{{ item.volname }}"
     bricks: "{{ item.brick }}"
     master: "{{ gluster_features_hci_master | default(omit) }}"
     port: "{{ gluster_features_hci_port | default(omit) }}"
     replicas: 3
     transport: tcp
     arbiters: "{{ item.arbiter | default(omit) }}"
     force: yes
     cluster: "{{ gluster_features_hci_cluster }}"
     options: "{{ gluster_features_hci_volume_options | default(omit) }}"
  run_once: true
  with_items: "{{ gluster_features_hci_volumes }}"

# gluster_volume does not support `gluster heal' command which gluster
# has implemented as an exception.
- name: Set granual-entry-heal on
  command: >
     gluster volume heal "{{item.volname}}" granular-entry-heal enable
  run_once: true
  with_items: "{{ gluster_features_hci_volumes }}"
  when: gluster_features_hci_master is not defined