---
# tasks file for gluster_hci
- name: Pre-requisites for setting up Gluster HCI
  import_tasks: prerequisites.yml
  tags:
    - prerequisites

# Setup glusterd slice
- name: Setup slice for glusterd
  import_tasks: slice_setup.yml
  when: gluster_features_slice_setup|default(true)
  tags:
    - setupslice

# Create GlusterFS volumes on the nodes
- name: Create GlusterFS volumes
  import_tasks: hci_volumes.yml
  tags:
    - hcivolcreate
