---
# tasks file for gluster_hci
- name: Pre-requisites for setting up Gluster HCI
  import_tasks: prerequisites.yml
  tags:
    - prerequisites

# Setup glusterd slice
- name: Setup slice for glusterd
  import_tasks: slice_setup.yml
  when: gluster_features_slice_setup|default(true)
  tags:
    - setupslice

# Configure glusterd to use ipv6.
# Don't try to configure if FQDN is not set.
- name: Configure glusterd to use ipv6
  import_tasks: glusterd_ipv6.yml
  when: gluster_features_enable_ipv6 | default(false)
  tags:
    - setupipv6

# Create GlusterFS volumes on the nodes
- name: Create GlusterFS volumes
  import_tasks: hci_volumes.yml
  tags:
    - hcivolcreate

# Run pre-requisite check for deploying Hosted Engine
- name: Check disk latency
  import_tasks: hosted_engine_pre_check.yml
  tags:
    - latencycheck