---
# Slice directory
- set_fact:
     slice_dir: /etc/systemd/system/glusterd.service.d

# Gather necessary facts
- name: Gather facts about the CPU
  setup:
     gather_subset:
        - '!all'
        - '!any'
        - processor
        - distribution

- name: Setup glusterd slice
  block:
     - name: Create the slice directory
       file:
          path: "{{ slice_dir }}"
          state: directory

     - name: Create cpu.conf file
       template:
          src: 99-cpu.conf
          dest: "{{ slice_dir }}"

     - name: Create glusterfs.slice file
       template:
          src: glusterfs.slice
          dest: /etc/systemd/system/

     - name: Reload the systemd daemon
       systemd:
          daemon-reload: yes
  when: ansible_os_family == "RedHat"
